webapp/amazon/urls.py
from django.urls import path

from .views import (ProductListView,
                    ProductDetailSlugView,
                    CategoryListView,
                    ProductByCategoryView,
                    list_package,
                    package_detail,
                    )
app_name="amazon"

urlpatterns = [
    path('products/', ProductListView.as_view(), name='list'),
    #path('products-fbv/', product_list_view),
    #path('products/<int:pk>/', ProductDetailView.as_view()),
    path('products/<slug:slug>/', ProductDetailSlugView.as_view(), name='detail'),
    #path('products-fbv/<int:pk>/', product_detail_view),
    path('package/', list_package, name='list-package'),
    path('package/<int:packageID>/', package_detail, name='package_detail'),
    path('category/', CategoryListView.as_view(), name='category'),
    path('category/<str:categoryName>/', ProductByCategoryView.as_view(), name='productsByCategory'),
]

webapp/carts/urls.py
from django.urls import path

from .views import (cart_home,
                    cart_update,
                    checkout_home,
                    )
app_name = "carts"

urlpatterns = [
    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),

]

webapp/webapp/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from accounts.views import register_page
from .views import home_page, about_page, contact_page
from carts.views import success

urlpatterns = [
    path('', home_page, name='home'),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', register_page, name='register'),
    path('', include('amazon.urls', namespace='amazon')),
    path('search/', include('search.urls', namespace='search')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('success/', success, name='success'),
    path('admin/', admin.site.urls),
]

#<slug:slug>
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/carts/models.py
import math
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import pre_save, m2m_changed

from amazon.models import Product


# Create your models here.
class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            #print('Cart ID exists')
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)

class Cart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    products = models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(default=0.00, max_digits=19, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=19, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, null=True, blank=True, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, blank=True, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)

    def __str__(self):
        return str(self.cart)+", "+str(self.product)

#action: pre_remove, post_add. pre_add...
# def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
#     #update total only when the following actions occur
#     if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
#         products = instance.products.all()
#         cartProducts = CartProduct.objects.filter(cart=instance)
#         total = 0
#         for x in cartProducts:
#             unit = x.product.price * x.count
#             total += unit
#         if instance.subtotal != total:
#             instance.subtotal = total
#             instance.save()
# #called when the obj is being saved
# #sender = many2many field. through
# m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)

# def pre_save_changed_cart_receiver(sender, instance, *args, **kwargs):
#     cartProducts = CartProduct.objects.filter(cart=instance)
#     print(cartProducts)
#     total = 0
#     for x in cartProducts:
#         unit = x.product.price
#         total += unit
#     print("total ", total)
#     if instance.subtotal != total:
#         instance.subtotal = total
#         instance.save()
#
# pre_save.connect(pre_save_changed_cart_receiver, sender=Cart)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal == 0:
        instance.total = 0.00
    else:
        #include tax (12%)
        new_total = float(instance.subtotal) * float(1.12)
        instance.total = format(new_total, '.2f')

pre_save.connect(pre_save_cart_receiver, sender=Cart)

webapp/carts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from amazon.models import Product, UserProduct, Package
from accounts.models import GuestEmail
from billing.models import BillingProfile
from .models import Cart, CartProduct
from orders.models import Order
from accounts.forms import LoginForm, GuestForm
from .utils import send

# Create your views here.
def cart_create(user=None):
    cart_obj = Cart.objects.create(user=None)
    print('create new cart')
    return cart_obj

def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    cartProducts = CartProduct.objects.filter(cart=cart_obj)
    total = 0
    for x in cartProducts:
        unit = x.product.price * x.count
        total += unit
    print("total ", total)
    if cart_obj.subtotal != total:
        cart_obj.subtotal = format(total, '.2f')
        cart_obj.save()
    return render(request, "carts/home.html", {"cart": cart_obj, "cartProducts": cartProducts})

def cart_update(request):
    #print(request.POST)
    product_id = request.POST.get('product')
    qty = request.POST.get('qty')
    print('qty')
    print(qty)
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("Show message to user, product is gone")
            return redirect("carts:home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        #remove
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            cartProduct_qs = CartProduct.objects.filter(cart=cart_obj)
            for cartProduct in cartProduct_qs:
                if cartProduct.product.id == product_obj.id:
                    cartProduct.delete()
        #add
        else:
            #many to many field
            cart_obj.products.add(product_obj) #  cart_obj.products.add(product_id)
            if qty:
                cartProduct = CartProduct.objects.create(cart=cart_obj, product=product_obj, count=qty)
            else:
                cartProduct = CartProduct.objects.create(cart=cart_obj, product=product_obj, count=1)
            cartProduct.save()
        request.session['cart_items'] = cart_obj.products.count()
    return redirect("carts:home")

@login_required
def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("carts:home")
    user = request.user
    billing_profile = None
    login_form = LoginForm()
    if user.is_authenticated:
        billing_profile, billing_profile_created = BillingProfile.objects.get_or_create(user=user, email=user.email)
    order_qs = Order.objects.filter(cart=cart_obj, active=True)
    if order_qs.exists():
        order_obj = order_qs.first()
    else:
        order_obj = Order.objects.create(billing_profile=billing_profile, cart=cart_obj)

    if request.method == "POST":
        x = int(request.POST["x"])
        y = int(request.POST["y"])
        #each package has one product
        packageID_lst = []
        for product in cart_obj.products.all():
            productID = product.id
            warehouseID = product.whnum.id
            curr_package = Package.objects.create(owner=user,
                                                dest_x=x,
                                                dest_y=y,
                                                warehouse=warehouseID
                                                )
            curr_package.save()
            packageID_lst.append(curr_package.pk)
            cartProduct = CartProduct.objects.filter(cart=cart_obj, product=product).first()
            if cartProduct:
                userProduct = UserProduct.objects.create(productID=product,
                                                         count=cartProduct.count,
                                                         package=curr_package
                                                         )
            else:
                userProduct = UserProduct.objects.create(productID=product,
                                                         count=1,
                                                         package=curr_package
                                                         )
            userProduct.save()
        #delete orders and update cart
        order_obj.delete()
        cart_obj.delete()
        #send to backend
        send(packageID_lst)

        request.session['cart_items'] = 0
        return redirect("success")
    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form
    }
    return render(request, "carts/checkout.html", context)

def success(request):
    return render(request, "carts/success.html", {})


# for product in cart_obj.products.all():
#     productID = product.id
#     warehouseID = product.whnum.id
#     if warehouseID in whDict.keys():
#         whDict[warehouseID].append(product)
#     else:
#         whDict[warehouseID] = [product]
# # create package
# print(whDict)
# packageID_lst = []
# for key, value_lst in whDict.items():
#     curr_package = Package.objects.create(owner=user,
#                                           dest_x=x,
#                                           dest_y=y,
#                                           warehouse=key
#                                           )
#     curr_package.save()
#     # add userProduct
#     for i in value_lst:
#         userProduct = UserProduct.objects.create(productID=i,
#                                                  count=1,
#                                                  package=curr_package
#                                                  )
#         userProduct.save()
#         cart_obj.products.remove(i)
#     id = curr_package.pk
#     packageID_lst.append(id)

webapp/carts/templates/carts/checkout.html
{% extends "base.html" %}

{% block content %}
<!--{{ object.order_id }} &#45;&#45; {{ object.cart }}-->

{% if not billing_profile %}
    <div class="row">
        <div class="col-12 col-md-8">
            <p class="lead">Login</p>
            {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
        </div>
        <div class="col-12 col-md-2">
            Continue as Guest
        </div>
    </div>
{% else %}

<h1>Checkout</h1>
<div class="row">
    <div class="col-md-5 order-md-2">
        <form method="POST">{% csrf_token %}
            <div class="form-group">
                <label for="inputAddress_x">Address X</label>
                <input  type="number" min=0 max=150 class="form-control" name="x" id="inputAddress_x" placeholder="x coordinate" required>
                 <div class="invalid-feedback" style="width: 100%;">
                                X value is required.
                            </div>
              </div>
              <div class="form-group">
                <label for="inputAddress_y">Address Y</label>
                <input  type="number" min=0 max=150 class="form-control" name="y" id="inputAddress_y" placeholder="y coordinate" required>
                   <div class="invalid-feedback" style="width: 100%;">
                                Y value is required.
                            </div>
              </div>

            <h4 class="mb-3">Payment</h4>

            <div class="d-block my-3">
                <div class="custom-control custom-radio">
                    <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked=""
                           required>
                    <label class="custom-control-label" for="credit">Credit card</label>
                </div>
                <div class="custom-control custom-radio">
                    <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required>
                    <label class="custom-control-label" for="debit">Debit card</label>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="cc-name">Name on card</label>
                    <input type="text" class="form-control" id="cc-name" placeholder="" required="" value="ece568">
                    <small class="text-muted">Full name as displayed on card</small>
                    <div class="invalid-feedback">
                        Name on card is required
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="cc-number">Credit card number</label>
                    <input type="text" class="form-control" id="cc-number" placeholder="" required="" value="12345">
                    <div class="invalid-feedback">
                        Credit card number is required
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3 mb-3">
                    <label for="cc-expiration">Expiration</label>
                    <input type="text" class="form-control" id="cc-expiration" placeholder="" required=""
                           value="08/23">
                    <div class="invalid-feedback">
                        Expiration date required
                    </div>
                </div>
                <div class="col-md-3 mb-3">
                    <label for="cc-cvv">CVV</label>
                    <input type="text" class="form-control" id="cc-cvv" placeholder="" required="" value="123">
                    <div class="invalid-feedback">
                        Security code required
                    </div>
                </div>
            </div>
            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Place order</button>

        </form>

    </div>

    <!-- side bar, show package info -->
    <div class="col-md-4 order-md-2">
        <ul class="list-group mb-3">
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">Price</h6>
                    </div>
                    <span class="text-muted">&dollar;</span>
                </li>
            <li class="list-group-item d-flex justify-content-between">
                <span>Cart Total (USD)</span>
                <strong>&dollar; {{ object.cart.total}}</strong>
            </li>
            <li class="list-group-item d-flex justify-content-between">
                <span>Shipping Total (USD)</span>
                <strong>&dollar; {{ object.shipping_total }}</strong>
            </li>
            <li class="list-group-item d-flex justify-content-between">
                <span>Order Total (USD)</span>
                <strong>&dollar; {{ object.total}}</strong>
            </li>
        </ul>
    </div>
</div>

{% endif %}

{% endblock %}

webapp/carts/templates/carts/home.html
{% extends "base.html" %}

{% block content %}
<h1>Cart</h1>
{% if cart.products.exists %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product Name</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Qty</th>
    </tr>
  </thead>
  <tbody>
    {% for product in cart.products.all %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td><a href="{{ product.get_absolute_url }}">{{ product.title|title }}</a>

        {% include 'amazon/snippets/update-cart.html' with product=product cart=cart in_cart=True%}
      <td>&dollar;{{ product.price }}</td>
      {% for cartProduct in cartProducts %}
        {% if cartProduct.product.id is product.id %}
          <td>{{ cartProduct.count }}</td>
        {% endif %}
      {% endfor %}
    </tr>
    {% endfor %}
    <tr>
      <th colspan="3"></th>
      <td><b>Subtotal: </b>&dollar;{{ cart.subtotal }}</td>
    </tr>
    <tr>
      <th colspan="3"></th>
      <td><b>Total(tax included): </b>&dollar;{{ cart.total }}</td>
    </tr>
      <tr>
      <th colspan="3"></th>
      <td><a href="{% url 'amazon:list' %}" class="btn btn-primary">Add More</a>
        <a class="btn btn-block btn-success" href="{% url 'carts:checkout' %}">Checkout</a></td>
    </tr>

  </tbody>
</table>
{% else %}
<p class="lead">Cart is empty</p>

{% endif %}

{% endblock %}

webapp/carts/templates/carts/success.html
{% extends "base.html" %}

{% block content %}
    <!-- success page, show success info -->
    <h1>Your order has been placed!</h1>

    <h2 class="mt-4"><a href="{% url 'home' %}">Buy more?</a></h2>

{% endblock %}