webapp/amazon/urls.py
from django.urls import path

from .views import (ProductListView,
                    ProductDetailSlugView,
                    CategoryListView,
                    ProductByCategoryView,
                    list_package,
                    package_detail,
                    )
app_name="amazon"

urlpatterns = [
    path('products/', ProductListView.as_view(), name='list'),
    #path('products-fbv/', product_list_view),
    #path('products/<int:pk>/', ProductDetailView.as_view()),
    path('products/<slug:slug>/', ProductDetailSlugView.as_view(), name='detail'),
    #path('products-fbv/<int:pk>/', product_detail_view),
    path('package/', list_package, name='list-package'),
    path('package/<int:packageID>/', package_detail, name='package_detail'),
    path('category/', CategoryListView.as_view(), name='category'),
    path('category/<str:categoryName>/', ProductByCategoryView.as_view(), name='productsByCategory'),
]

webapp/carts/urls.py
from django.urls import path

from .views import (cart_home,
                    cart_update,
                    checkout_home,
                    )
app_name = "carts"

urlpatterns = [
    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),

]

webapp/webapp/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from accounts.views import register_page
from .views import home_page, about_page, contact_page
from carts.views import success

urlpatterns = [
    path('', home_page, name='home'),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', register_page, name='register'),
    path('', include('amazon.urls', namespace='amazon')),
    path('search/', include('search.urls', namespace='search')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('success/', success, name='success'),
    path('admin/', admin.site.urls),
]

#<slug:slug>
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<!-- Fontawesome CSS-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css" />

webapp/templates/base/js.html
{% load static %}
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->

webapp/templates/base/navbar.html
{% load static %}
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'amazon:list' as amazon_list_url %}
{% url 'amazon:category' as amazon_category_url %}
{% url 'amazon:list-package' as amazon_list_package %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'carts:home' as cart_url %}

<script src="https://kit.fontawesome.com/b7682e0007.js" crossorigin="anonymous"></script>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container">
    <a class="navbar-brand" href={{ home_url }}>
<!--      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">-->
      <i class="fa-brands fa-amazon"></i>
      {% if brand_name %}{{ brand_name }} {% else %}MiniAmazon{% endif %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item {% if request.path == home_url %}active{% endif %}">
          <a class="nav-link" href="{{ home_url }}"><i class="fa-solid fa-house"></i> Home</a>
        </li>
<!--        <li class="nav-item {% if request.path == contact_url %}active{% endif %}">-->
<!--          <a class="nav-link" href="{{ contact_url }}">Contacts</a>-->
<!--        </li>-->
        <li class="nav-item {% if request.path == amazon_list_url %}active{% endif %}">
          <a class="nav-link" href="{{ amazon_list_url }}">Products</a>
        </li>
        <li class="nav-item {% if request.path == amazon_category_url %}active{% endif %}">
          <a class="nav-link" href="{{ amazon_category_url }}">Categories</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
          <a class="nav-link" href="{{ home_url }}">welcome {{ request.user }}</i></a>
        </li>
        <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
          <a class="nav-link" href="{{ amazon_list_package }}">My Package</a>
        </li>
          <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
            <a class="nav-link" href="{{ logout_url }}"><i class="fa-solid fa-arrow-right-from-bracket"></i> Logout</a>
          </li>

        {% else %}
          <li class="nav-item {% if request.path == login_url %}active{% endif %}">
              <a class="nav-link" href="{{ login_url }}"><i class="fa-solid fa-arrow-right-to-bracket"></i> Login</a>
          </li>
          <li class="nav-item {% if request.path == register_url %}active{% endif %}">
              <a class="nav-link" href="{{ register_url }}"><i class="fa-solid fa-user-plus"></i> Register</a>
          </li>
        {% endif %}
        <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
          <a class="nav-link" href="{{ cart_url }}">{{ request.session.cart_items }} <i class="fa-solid fa-cart-shopping"></i></a>
        </li>
<!--        <li class="nav-item dropdown">-->
<!--          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--            Dropdown-->
<!--          </a>-->
<!--          <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--            <a class="dropdown-item" href="#">Action</a>-->
<!--            <a class="dropdown-item" href="#">Another action</a>-->
<!--            <div class="dropdown-divider"></div>-->
<!--            <a class="dropdown-item" href="#">Something else here</a>-->
<!--          </div>-->
<!--        </li>-->
      </ul>
      {% include 'search/snippets/search-form.html' %}
    </div>
  </div>
</nav>